AWSTemplateFormatVersion: 2010-09-09

Description: |
  Phone book Application (Python Flask) deployed on AWS EC2 with Cloudformation.

Parameters:
  myKeyPair:
    Description: Select your key
    Type: AWS::EC2::KeyPair::KeyName

  myAMI:
    Description: The id of the AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  myVPC:
    Description: Select your VPC
    Type: AWS::EC2::VPC::Id  
  
Resources:
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Flask Web Server and SSH port to secure reach to my EC2 # Required
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  dbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL to DB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      VpcId: !Ref myVPC

          
          
  myServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref myAMI
      KeyName: !Ref myKeyPair
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref mySecurityGroup 
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData: 
        Fn::Base64: !Sub 
        - |
          #! /bin/bash
          sleep 2m
          yum update -y
          sudo pip3 install flask flask-mysql sqlalchemy flask-SQLAlchemy
          cd /home/ec2-user
          touch dbserver.endpoint && echo "endpoint" > dbserver.endpoint
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-004-Phonebook-Application/phonebook-app.py
          wget -P templates https://raw.githubusercontent.com/ayse16/my_projects/main/Project-004-Phonebook-Application/templates/add-update.html
          wget -P templates https://raw.githubusercontent.com/ayse16/my_projects/main/Project-004-Phonebook-Application/templates/delete.html
          wget -P templates https://raw.githubusercontent.com/ayse16/my_projects/main/Project-004-Phonebook-Application/templates/index.html
          sed -i -e 's/endpoint/${DBEndPoint}/g' /home/ec2-user/dbserver.endpoint
          python3 phonebook-app.py
        - DBEndPoint: 
            Fn::GetAtt: [ "dbserver","Endpoint.Address" ]
            
         
          
       
  dbserver:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: myRdsDB
      DBInstanceClass: db.t2.micro # Required
      DBName: clarusway_phonebook
      VPCSecurityGroups:
        - !Ref dbSecurityGroup
      Engine: MySQL
      EngineVersion: 8.0.19
      MasterUserPassword: Clarusway_Project4
      MasterUsername: admin
      AllocatedStorage: "20"
      MultiAZ: false
      Port: 3306
      StorageType: standard
      
      
Outputs:
  WebsiteUrl:
    Description: Phonebook Application URL
    Value: !Join 
       - ''
       - - 'http://'
         - !GetAtt myServer.PublicDnsName
  
  DBEndPoint:
    Description: A reference to the End point of DBInstance
    Value: { "Fn::GetAtt": [ "dbserver","Endpoint.Address" ] }
    Export:
       Name: !Sub "DBEndPoint"  
  

  
         

