AWSTemplateFormatVersion: 2010-09-09

Description: | 
  This template launches an EC2 instance by using CloudFormation 

Resources:
  WEBServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - ssh+http
      Tags:
        - Key: Name
          Value: WebServer-Instance
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y
          #install apache server
          yum install -y httpd
          cd /var/www/html
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/ayse16/my_projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png
          # start apache server
          systemctl start httpd
          systemctl enable httpd
Outputs:
  WebisteUrl:
    Description: Kittenn Carousel's URL address
    Value: !GetAtt WEBServerInstance.PublicDnsName
  
            
  


   
           




  

